---
- name: Dependencies installation for InvenioDRM
  hosts: invent
  become: true
  become_method: sudo

  tasks:
    - name: Update system
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Install Basic tools
      ansible.builtin.package:
        name:
          - curl
          - wget
          - vim
          - git
          - python3
          - python3-venv
          - python3-pip
          - python3-dev
          - imagemagick
          - fonts-dejavu
        state: present

    - name: Development tools
      ansible.builtin.package:
        name:
          - build-essential
          - linux-source
          - gcc 
          - make
          - bzip2 
          - perl 
        state: present
